#!/usr/bin/env bash
set -euo pipefail

# Resolve the latest stable upstream tags without placing credentials in Git.
# The output is intended for the private deployment repository, not the public
# repository. A resolved file is a deployment lock, not a floating upgrade.

OUTPUT_FILE=${VERSION_FILE:-}
ASTRBOT_REPO=${ASTRBOT_REPO:-https://github.com/AstrBotDevs/AstrBot.git}
SNOWLUMA_REPO=${SNOWLUMA_REPO:-https://github.com/SnowLuma/SnowLuma.git}

need() { command -v "$1" >/dev/null 2>&1 || { echo "required command not found: $1" >&2; exit 1; }; }
need git

latest_tag() {
  local repo=$1
  git ls-remote --tags --sort='-v:refname' "$repo" 'v[0-9]*' \
    | awk '!/\^\{\}$/ {sub("refs/tags/", "", $2); print $2; exit}'
}

tag_commit() {
  local repo=$1 tag=$2 peeled
  peeled=$(git ls-remote "$repo" "refs/tags/${tag}^{}" | awk 'NR == 1 {print $1}')
  if [[ -n "$peeled" ]]; then
    printf '%s\n' "$peeled"
  else
    git ls-remote "$repo" "refs/tags/${tag}" | awk 'NR == 1 {print $1}'
  fi
}

ASTRBOT_TAG=${ASTRBOT_TAG:-$(latest_tag "$ASTRBOT_REPO")}
SNOWLUMA_TAG=${SNOWLUMA_TAG:-$(latest_tag "$SNOWLUMA_REPO")}
[[ -n "$ASTRBOT_TAG" ]] || { echo 'could not resolve AstrBot stable tag' >&2; exit 1; }
[[ -n "$SNOWLUMA_TAG" ]] || { echo 'could not resolve SnowLuma stable tag' >&2; exit 1; }

ASTRBOT_COMMIT=$(tag_commit "$ASTRBOT_REPO" "$ASTRBOT_TAG")
SNOWLUMA_COMMIT=$(tag_commit "$SNOWLUMA_REPO" "$SNOWLUMA_TAG")
[[ "$ASTRBOT_COMMIT" =~ ^[0-9a-f]{40}$ ]] || { echo 'invalid AstrBot commit resolved' >&2; exit 1; }
[[ "$SNOWLUMA_COMMIT" =~ ^[0-9a-f]{40}$ ]] || { echo 'invalid SnowLuma commit resolved' >&2; exit 1; }

SNOWLUMA_IMAGE=${SNOWLUMA_IMAGE:-snowluma-local:${SNOWLUMA_TAG#v}}
generated_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

if [[ -z "$OUTPUT_FILE" ]]; then
  printf 'ASTRBOT_TAG=%s\nASTRBOT_COMMIT=%s\nSNOWLUMA_TAG=%s\nSNOWLUMA_COMMIT=%s\nSNOWLUMA_IMAGE=%s\n' \
    "$ASTRBOT_TAG" "$ASTRBOT_COMMIT" "$SNOWLUMA_TAG" "$SNOWLUMA_COMMIT" "$SNOWLUMA_IMAGE"
else
  umask 077
  mkdir -p "$(dirname -- "$OUTPUT_FILE")"
  cat >"$OUTPUT_FILE" <<EOF
# Generated by deploy/resolve-latest-versions.sh at ${generated_at}
# Keep this file in the private deployment repository.
ASTRBOT_REPO=${ASTRBOT_REPO}
ASTRBOT_TAG=${ASTRBOT_TAG}
ASTRBOT_COMMIT=${ASTRBOT_COMMIT}
SNOWLUMA_REPO=${SNOWLUMA_REPO}
SNOWLUMA_TAG=${SNOWLUMA_TAG}
SNOWLUMA_COMMIT=${SNOWLUMA_COMMIT}
SNOWLUMA_IMAGE=${SNOWLUMA_IMAGE}
EOF
  chmod 600 "$OUTPUT_FILE"
  printf 'wrote %s\n' "$OUTPUT_FILE"
fi
