"""Cognitive Runtime compatibility layer for Iris.

This package owns only the new runtime views and deterministic identity state.
It never mutates existing Iris L1--L3 records or AstrBot Persona.
"""

from .contracts import (
    CanonicalEntity,
    CanonicalExperience,
    CognitiveContractError,
    EntityReference,
    EntityType,
    EventExecutionContext,
    ExitReason,
    BehaviorLoopResult,
    BehaviorExecutionRecord,
    BehaviorTrace,
    DeliveryStatus,
    DivergenceType,
    GroundingEnforcement,
    GroundingResult,
    GroundingStatus,
    IdentityClaim,
    IdentityClaimStatus,
    IdentityConfig,
    IdentityStore,
    Intent,
    IntentDomain,
    IrisPreprocessResult,
    LegacyProactiveSignals,
    ParticipationDecision,
    ParticipationResult,
    Perspective,
    ResolvedEvent,
    RuntimeMemoryView,
    RuntimeMode,
    OutputState,
    OutputProducer,
    ShadowComparison,
    HostResult,
    RealizerRequest,
    SocialAction,
    Situation,
    SituationFull,
    SituationLite,
    TriggerSnapshot,
    TriggerDecision,
    TraceStage,
    canonical_tuple,
    to_json_safe,
)
from .behavior import CognitiveBehaviorRuntime, GroundingGuard, IntentPlanner, ParticipationController
from .legacy_proactive import LegacyIrisProactiveSignalAdapter
from .iris_adapter import CognitiveRuntime, IrisPostAdapter, IrisPreAdapter, get_cognitive_runtime
from .replay import LocalHistoricalReplayRunner
from .situation import SituationBuilder
from .trigger import TriggerController
from .episode import (
    BoundaryAction,
    Episode,
    EpisodeBoundaryDecision,
    EpisodeEventKind,
    EpisodeEventRef,
    EpisodeState,
    make_episode_event_ref_id,
    make_episode_id,
)
from .outcome import (
    OutcomeExplicitness,
    OutcomeKind,
    OutcomeObservation,
    make_outcome_observation_id,
)
from .episode_store import (
    AppendOnlyEpisodeStore,
    InMemoryEpisodeStore,
)
from .episode_assembler import EpisodeAssembler
from .outcome_collector import OutcomeCollector
from .episode_shadow import EpisodeShadowObserver
from .review import (
    AttributionRef,
    AttributionTargetType,
    BehaviorScope,
    CausalAttribution,
    Confidence,
    EvidenceKind,
    EvidenceSourceType,
    FindingType,
    InterpretationProducer,
    LocalEvidenceProposition,
    ReviewDimension,
    ReviewEligibility,
    ReviewEligibilityDecision,
    ReviewEvidence,
    ReviewEvidenceRef,
    ReviewFinding,
    ReviewRun,
    ReviewStatus,
)
from .review_service import (
    DeterministicReviewEngine,
    ReviewFactResolver,
    ReviewInputSnapshot,
    StructuredModelReviewEngine,
    compute_input_snapshot_hash,
    evaluate_review_eligibility,
    model_version_fallback,
    promote_finding_to_evidence,
    review_episode,
    validate_finding_grounding,
    validate_model_provenance,
    validate_proposition_safe,
)
from .review_store import AppendOnlyReviewStore, InMemoryReviewStore
from .execution_observatory import ExecutionRecordObservatory

__all__ = [
    "CanonicalEntity",
    "CanonicalExperience",
    "CognitiveContractError",
    "EntityReference",
    "EntityType",
    "EventExecutionContext",
    "ExitReason",
    "BehaviorLoopResult",
    "BehaviorExecutionRecord",
    "BehaviorTrace",
    "DeliveryStatus",
    "DivergenceType",
    "GroundingEnforcement",
    "GroundingResult",
    "GroundingStatus",
    "IdentityClaim",
    "IdentityClaimStatus",
    "IdentityConfig",
    "IdentityStore",
    "Intent",
    "IntentDomain",
    "IrisPreprocessResult",
    "LegacyProactiveSignals",
    "ParticipationDecision",
    "ParticipationResult",
    "Perspective",
    "ResolvedEvent",
    "RuntimeMemoryView",
    "RuntimeMode",
    "OutputState",
    "OutputProducer",
    "ShadowComparison",
    "HostResult",
    "RealizerRequest",
    "SocialAction",
    "Situation",
    "SituationFull",
    "SituationLite",
    "TriggerSnapshot",
    "TriggerDecision",
    "TraceStage",
    "canonical_tuple",
    "to_json_safe",
    "CognitiveRuntime",
    "IrisPostAdapter",
    "IrisPreAdapter",
    "get_cognitive_runtime",
    "SituationBuilder",
    "TriggerController",
    "CognitiveBehaviorRuntime",
    "GroundingGuard",
    "IntentPlanner",
    "ParticipationController",
    "LegacyIrisProactiveSignalAdapter",
    "LocalHistoricalReplayRunner",
    "BoundaryAction",
    "Episode",
    "EpisodeBoundaryDecision",
    "EpisodeEventKind",
    "EpisodeEventRef",
    "EpisodeState",
    "OutcomeExplicitness",
    "OutcomeKind",
    "OutcomeObservation",
    "InMemoryEpisodeStore",
    "AppendOnlyEpisodeStore",
    "EpisodeAssembler",
    "OutcomeCollector",
    "EpisodeShadowObserver",
    "make_episode_id",
    "make_episode_event_ref_id",
    "make_outcome_observation_id",
    "AttributionRef",
    "AttributionTargetType",
    "BehaviorScope",
    "CausalAttribution",
    "Confidence",
    "EvidenceKind",
    "EvidenceSourceType",
    "FindingType",
    "InterpretationProducer",
    "LocalEvidenceProposition",
    "ReviewDimension",
    "ReviewEligibility",
    "ReviewEligibilityDecision",
    "ReviewEvidence",
    "ReviewEvidenceRef",
    "ReviewFinding",
    "ReviewRun",
    "ReviewStatus",
    "ReviewFactResolver",
    "ReviewInputSnapshot",
    "DeterministicReviewEngine",
    "StructuredModelReviewEngine",
    "compute_input_snapshot_hash",
    "evaluate_review_eligibility",
    "model_version_fallback",
    "promote_finding_to_evidence",
    "review_episode",
    "validate_finding_grounding",
    "validate_model_provenance",
    "validate_proposition_safe",
    "InMemoryReviewStore",
    "AppendOnlyReviewStore",
    "ExecutionRecordObservatory",
]
